spring:
  datasource:
    url: jdbc:mysql://localhost:3306/harmony_band?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdata



